version : '3'

services :
  db :
    container_name: my-db
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=jgjzvs
      - POSTGRES_PASSWORD=011245
    image: postgres:14.4
    restart: unless-stopped

  pgadmin :
    container_name : pg-admin
    ports:
      - 4433:443
      - 8080:80
    environment :
      - PGADMIN_DEFAULT_EMAIL=jgjzvs@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=011245
    image : dpage/pgadmin4:latest
    restart : unless-stopped

  strapi :
    container_name : my-app
    ports:
      - 1337:1337
    environment :
      - name=value
      - DATABASE_CLIENT=postgres
      - DATABASE_PORT=54321
      - DATABASE_NAME=jgjzvs
      - DATABASE_HOST=192.168.1.105
      - DATABASE_USERNAME=jgjzvs
      - DATABASE_PASSWORD=011245
      - DATABASE_SSL=false
    image: 'naskio/strapi:latest'  
    restart: 'unless-stopped' 